lib/click_game_web/router.ex
defmodule ClickGameWeb.Router do
  use ClickGameWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  #pipeline :player_api do
    #plug :accepts, ["json"]
    #plug ClickGameWeb.Plugs.LoadUser
  #end

  #pipeline :admin_api do
    #plug :accepts, ["json"]
  #end

  pipeline :user_loader do
    plug ClickGameWeb.Plugs.LoadUser
    plug :put_socket_token
  end

  defp put_socket_token(conn, _) do
    if current_user = conn.assigns[:user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  scope "/", ClickGameWeb do
    pipe_through :browser
    pipe_through :user_loader

    get "/", PageController, :index
    get "/login", SessionController, :new
    get "/signup", UserController, :new
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
    resources "/users", UserController, only: [:create, :delete], singleton: true
    get "/game/:id", GameController, :view
  end

  # Other scopes may use custom stacks.
  #scope "/api/admin/", ClickGameWeb do
    #pipe_through :admin_api
    ##resources "/users", UserController, except: [:new, :edit]
  #end

  #scope "/api/player/", ClickGameWeb do
    #pipe_through :player_api
    #get "/game_url", GameController, :game_url
    #get "/clicks", GameController, :clicks
    #get "/click", GameController, :click
    ## get "/click/:side", GameController, :click
    #get "/store/clickers", StoreController, :clickers
    #get "/store/upgrades", StoreController, :upgrades
    #get "/store", StoreController, :store
    #get "/store/clickers/buy/:id", StoreController, :buy_clicker
    ## resources "/game", UserController, :game
  #end
end

lib/click_game_web/views/layout_view.ex
defmodule ClickGameWeb.LayoutView do
  use ClickGameWeb, :view

  def is_logged(conn) do
    ClickGameWeb.SessionController.is_logged(conn)
  end

  def js_files(conn) do
    conn.assigns[:js_files] || []
  end
end

lib/click_game_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ClickGame · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/main.css") %>"/>
  </head>
  <body class="font-mono h-full">
    <nav class="container mx-auto py-6 flex justify-end font-semibold" role="navigation">
      <ul class="inline-flex border border-black rounded p-3 text-gray-700">
        <li><a class="pr-4 hover:text-gray-400" href="/">home</a></li>
        <li><a class="hover:text-gray-400" href="/leaderboard">leaderboard</a></li>
        <%= if is_logged(@conn) do %>
          <li>
          <%= form_for @conn, Routes.session_path(@conn, :delete), [method: :delete, as: :user], fn _ -> %>
              <%= submit "logout" , [class: "pl-4 hover:text-gray-400 font-semibold"] %>
          <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
    <main role="main" class="container mx-auto h-full">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <%= for path <- js_files(@conn) do %>
      <script type="text/javascript" src="<%= Routes.static_path(@conn, path) %>"></script>
    <% end %>
  </body>
</html>