lib/click_game_web/router.ex
defmodule ClickGameWeb.Router do
  use ClickGameWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  #pipeline :player_api do
    #plug :accepts, ["json"]
    #plug ClickGameWeb.Plugs.LoadUser
  #end

  #pipeline :admin_api do
    #plug :accepts, ["json"]
  #end

  pipeline :user_loader do
    plug ClickGameWeb.Plugs.LoadUser
    plug :put_socket_token
  end

  defp put_socket_token(conn, _) do
    if current_user = conn.assigns[:user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  scope "/", ClickGameWeb do
    pipe_through :browser
    pipe_through :user_loader

    get "/", PageController, :index
    get "/login", SessionController, :new
    get "/signup", UserController, :new
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
    resources "/users", UserController, only: [:create, :delete], singleton: true
    get "/game/:id", GameController, :view
  end

  # Other scopes may use custom stacks.
  #scope "/api/admin/", ClickGameWeb do
    #pipe_through :admin_api
    ##resources "/users", UserController, except: [:new, :edit]
  #end

  #scope "/api/player/", ClickGameWeb do
    #pipe_through :player_api
    #get "/game_url", GameController, :game_url
    #get "/clicks", GameController, :clicks
    #get "/click", GameController, :click
    ## get "/click/:side", GameController, :click
    #get "/store/clickers", StoreController, :clickers
    #get "/store/upgrades", StoreController, :upgrades
    #get "/store", StoreController, :store
    #get "/store/clickers/buy/:id", StoreController, :buy_clicker
    ## resources "/game", UserController, :game
  #end
end

lib/click_game_web/controllers/session_controller.ex
defmodule ClickGameWeb.SessionController do
  use ClickGameWeb, :controller

  alias ClickGame.Accounts
  alias ClickGame.Accounts.User

  def is_logged(conn) do
    get_session(conn, :user_id) !== nil
  end

  def new(conn, _) do
    case get_session(conn, :user_id) do
      nil -> render(conn, "new.html")
      _ -> 
        conn
        |> redirect(to: "/")
    end
  end

  def create(conn, %{"user" => %{"name" => name, "pw" => pw}}) do
    case Accounts.auth_by_pw(name, pw) do
      %User{} = user ->
        conn
        |> put_flash(:info, "Hello " <> user.name)
        |> put_session(:user_id, user.id)
        |> configure_session(renew: true)
        |> redirect(to: "/")
      _ -> 
        conn
        |> put_flash(:error, "Bad name/password combination")
        |> redirect(to: Routes.session_path(conn, :new))
    end
  end

  def delete(conn, _) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: "/")
  end
end

lib/click_game_web/views/session_view.ex
defmodule ClickGameWeb.SessionView do
  use ClickGameWeb, :view
end

lib/click_game_web/templates/session/new.html.eex
<%#https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#text_input/3%>
<div class="border border-black mx-auto rounded p-4 mt-20">
  <h1 class="font-semibold text-2xl">Login</h1>

<%= form_for @conn, Routes.session_path(@conn, :create), [method: :post, as: :user, class: "mt-4"], fn f -> %>
<%#Map.put(assigns, :action, Routes.game_path(@conn, :create))%>
<%#<%= form_for @changeset, :create, fn f -> %>
  <%#<%= if @changeset.action do %>
    <%#<div class="alert alert-danger">%>
      <%#<p>Oops, something went wrong! Please check the errors below.</p>%>
    <%#</div>%>
  <%#<% end %>

  <%= label f, :name %>
  <%= text_input f, :name, [class: "rounded bg-gray-400 px-2 py-1"] %>
  <%= error_tag f, :name %>

  <%= label f, :password %>
  <%= password_input f, :pw, [class: "rounded bg-gray-400 px-2 py-1"] %>
  <%= error_tag f, :pw %>

  <div>
    <%= submit "Save", [class: "rounded bg-black text-white font-semibold px-4 py-2 hover:bg-white hover:text-black hover:border-black border mt-6"] %>
  </div>
<% end %>
</div>